controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Comments;
use yii\data\Pagination;
use app\models\CreateForm;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\Posts;
use app\models\ContactForm;
use app\models\RegForm;
use app\models\User;
use yii\data\ActiveDataProvider;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],

        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        //Yii::$app->session->addFlash('info', 'Test message');
        //Yii::$app->session->addFlash('danger', 'Test danger message');
        $provider = new ActiveDataProvider([
            'query' => Posts::find(),
            'pagination' => [
                'pageSize' => 3,
            ],
        ]);
        $provider = $provider->getModels();
        //$posts = Posts::find();
        //$count = $posts->count();
        //$pages = new Pagination(['totalCount' => $count, 'pageSize' => 3]);
        //$pages->pageSizeParam = false;
        //$posts = $posts->offset($pages->offset)->limit($pages->limit)->all();
        return $this->render('index', [
                'provider' => $provider,
                //'pages' => $pages,
            ]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionReg()
    {
        $model = new RegForm();
        if ($model->load(Yii::$app->request->post())) {
            $user = new User();
            $user->login = $model->login;
            $user->password = hash('ripemd128', $model->password1);
            if ($user->save() && $model->login()) {
                return $this->goHome();
            }
        }

        return $this->render('reg', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionCreate()
    {
        $model = new CreateForm();
        if ($model->load(Yii::$app->request->post()) && $model->addPost()) {
            Yii::$app->session->addFlash('info', 'Ваш пост успешно добавлен');
            return $this->goHome();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionDelete($id)
    {
        $model = Posts::findOne(['id' => $id]);
        $comments = $model->comments;
        if ($model->delete()) {
            foreach ($comments as $comment) {
                $comment->delete();
            }
            Yii::$app->session->addFlash('danger', 'Запись была удалена');
            return $this->goHome();
        }
    }

    public function actionEdit($id)
    {
        $model = Posts::findOne(['id' => $id]);
        if ($model->load(Yii::$app->request->post())) {
            $model->date = date('Y-m-d H:i:s');
            if ($model->save()) {
                Yii::$app->session->addFlash('info', 'Пост был успешно изменен');
                return $this->goHome();
            }
        }

        return $this->render('edit', [
            'model' => $model,
        ]);
    }

    public function actionView($id)
    {
        if ($post = Posts::findOne(['id' => $id])) {
            $model= new Comments();
            /*if ($model->load(Yii::$app->request->post())) {
                $model->date = date('Y-m-d H:i:s');
                $model->user_id = Yii::$app->user->id;
                $model->post_id = $id;
                $model->save();
                return $this->refresh();
            }*/

            return $this->render('view', [
                'post' => $post,
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/layouts/flash.php
<?php foreach(Yii::$app->session->getAllFlashes() as $type => $messages): ?>
    <?php foreach($messages as $message): ?>
        <div class="alert alert-<?= $type ?>" role="alert"><?= $message ?></div>
    <?php endforeach ?>
<?php endforeach ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => '<b>BL</b><span class="glyphicon glyphicon-info-sign"></span><b>G</b>!',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Новости', 'url' => ['/site/index']],
            [
                'label' => 'Войти',
                'url' => ['/site/login'],
                'visible' => Yii::$app->user->isGuest,
            ],
            [
                'label' => 'Регистрация',
                'url' => ['/site/reg'],
                'visible' => Yii::$app->user->isGuest,
            ],
            [
                'label' => 'Добавить новость',
                'url' => ['/site/create'],
                'visible' => !Yii::$app->user->isGuest,
            ],
            [
                'label' => '<span class="glyphicon glyphicon-log-out"></span> Выход',
                'url' => ['/site/logout'],
                'encode' => false,
                'visible' => !Yii::$app->user->isGuest,
            ],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            'encodeLabels' => false,
            'homeLink' => [
                'label' => 'Главная',
                'url' => ['site/index'],
            ]
        ]) ?>
        <?= $this->render('flash')?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>