controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Comments;
use yii\data\Pagination;
use app\models\CreateForm;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\Posts;
use app\models\ContactForm;
use app\models\RegForm;
use app\models\User;
use yii\data\ActiveDataProvider;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],

        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        //Yii::$app->session->addFlash('info', 'Test message');
        //Yii::$app->session->addFlash('danger', 'Test danger message');
        $provider = new ActiveDataProvider([
            'query' => Posts::find(),
            'pagination' => [
                'pageSize' => 3,
            ],
        ]);
        $provider = $provider->getModels();
        //$posts = Posts::find();
        //$count = $posts->count();
        //$pages = new Pagination(['totalCount' => $count, 'pageSize' => 3]);
        //$pages->pageSizeParam = false;
        //$posts = $posts->offset($pages->offset)->limit($pages->limit)->all();
        return $this->render('index', [
                'provider' => $provider,
                //'pages' => $pages,
            ]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionReg()
    {
        $model = new RegForm();
        if ($model->load(Yii::$app->request->post())) {
            $user = new User();
            $user->login = $model->login;
            $user->password = hash('ripemd128', $model->password1);
            if ($user->save() && $model->login()) {
                return $this->goHome();
            }
        }

        return $this->render('reg', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionCreate()
    {
        $model = new CreateForm();
        if ($model->load(Yii::$app->request->post()) && $model->addPost()) {
            Yii::$app->session->addFlash('info', 'Ваш пост успешно добавлен');
            return $this->goHome();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionDelete($id)
    {
        $model = Posts::findOne(['id' => $id]);
        $comments = $model->comments;
        if ($model->delete()) {
            foreach ($comments as $comment) {
                $comment->delete();
            }
            Yii::$app->session->addFlash('danger', 'Запись была удалена');
            return $this->goHome();
        }
    }

    public function actionEdit($id)
    {
        $model = Posts::findOne(['id' => $id]);
        if ($model->load(Yii::$app->request->post())) {
            $model->date = date('Y-m-d H:i:s');
            if ($model->save()) {
                Yii::$app->session->addFlash('info', 'Пост был успешно изменен');
                return $this->goHome();
            }
        }

        return $this->render('edit', [
            'model' => $model,
        ]);
    }

    public function actionView($id)
    {
        if ($post = Posts::findOne(['id' => $id])) {
            $model= new Comments();
            /*if ($model->load(Yii::$app->request->post())) {
                $model->date = date('Y-m-d H:i:s');
                $model->user_id = Yii::$app->user->id;
                $model->post_id = $id;
                $model->save();
                return $this->refresh();
            }*/

            return $this->render('view', [
                'post' => $post,
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/_post.php
<div class="container">
    <h3><?= $post->title ?></h3>
    <p><?= $post->text ?></p>
    <a href="<?= Url::to(['site/view', 'id' => $post->id]) ?>">комментарии <span class="badge"><?=count($post->comments)?></span></a>
    <?php
    if (!Yii::$app->user->isGuest) {
        echo "<br><br><a class='btn btn-danger' href='".Url::to(['site/delete', 'id' => $post->id])."' role='button'>Удалить</a>  ";
        echo "<a class='btn btn-warning' href='".Url::to(['site/edit', 'id' => $post->id])."' role='button'>Редактировать</a>";
    }

    ?>
    <hr>
</div>

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/create.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Добавить новость';
$this->params['breadcrumbs'][] = $this->title;
?>
<?php $form = ActiveForm::begin([
    'id' => 'create-form',
    'layout' => 'horizontal',
    'fieldConfig' => [
        'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
        'labelOptions' => ['class' => 'col-lg-1 control-label'],
    ],
]); ?>

<?= $form->field($model, 'title')->textInput(['autofocus' => true]) ?>

<?= $form->field($model, 'text')->textInput() ?>


<div class="form-group">
    <div class="col-lg-offset-1 col-lg-11">
        <?= Html::submitButton('Добавить', ['class' => 'btn btn-primary', 'name' => 'create-button']) ?>
    </div>
</div>

<?php ActiveForm::end(); ?>

views/site/edit.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
?>
<?php $form = ActiveForm::begin(); ?>

<?= $form->field($model, 'title')->textInput(['autofocus' => true]); ?>

<?= $form->field($model, 'text')->textInput(); ?>

<div class="form-group">
    <div class="col-lg-offset-1 col-lg-11">
        <?= Html::submitButton('Добавить', ['class' => 'btn btn-primary', 'name' => 'create-button']) ?>
    </div>
</div>

<?php ActiveForm::end(); ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
use yii\helpers\Url;
use yii\widgets\LinkPager;
use yii\widgets\ListView;

/*
foreach ($posts as $post) {
    ?>
    <div class="container">
        <h3><?= $post->title ?></h3>
        <p><?= $post->text ?></p>
        <a href="<?= Url::to(['site/view', 'id' => $post->id]) ?>">комментарии <span class="badge"><?=count($post->comments)?></span></a>
        <?php
        if (!Yii::$app->user->isGuest) {
            echo "<br><br><a class='btn btn-danger' href='".Url::to(['site/delete', 'id' => $post->id])."' role='button'>Удалить</a>  ";
            echo "<a class='btn btn-warning' href='".Url::to(['site/edit', 'id' => $post->id])."' role='button'>Редактировать</a>";
        }

        ?>
        <hr>
    </div>

    <?php
}
*/
//echo LinkPager::widget([
  //      'pagination' => $provider->pagination,
    //]);

echo ListView::widget([
    'provider' => $provider,
    'itemView' => '_post',
    'viewParams' => [
        'fullView' => true,
        'context' => 'main-page',
        // ...
    ],
]);

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Авторизация';
$this->params['breadcrumbs'][] = '<span class="glyphicon glyphicon-user"></span> Авторизация';
?>
    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'login')->textInput(['autofocus' => true]) ?>

    <?= $form->field($model, 'password')->passwordInput() ?>


    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

views/site/reg.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Регистрация';
$this->params['breadcrumbs'][] = $this->title;
?>
<?php $form = ActiveForm::begin([
    'id' => 'reg-form',
    'layout' => 'horizontal',
    'fieldConfig' => [
        'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
        'labelOptions' => ['class' => 'col-lg-1 control-label'],
    ],
]); ?>

<?= $form->field($model, 'login')->textInput(['autofocus' => true]) ?>

<?= $form->field($model, 'password1')->passwordInput() ?>
<?= $form->field($model, 'password2')->passwordInput() ?>

<?= $form->field($model, 'captcha')->widget(yii\captcha\Captcha::className(), [

])?>

<div class="form-group">
    <div class="col-lg-offset-1 col-lg-11">
        <?= Html::submitButton('Зарегистрироваться', ['class' => 'btn btn-primary', 'name' => 'reg-button']) ?>
    </div>
</div>

<?php ActiveForm::end(); ?>

views/site/view.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
$this->title = "Новость №{$post->id}";
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="container">
    <h3><?=$post->title?></h3>
    <br>
    <?=$post->text?>
    <br>
    <?=$post->date?>
    <hr>


    <?php
    echo '<b>комментарии к посту:<br></b>';
    foreach ($post->comments as $comment) {
    ?>
    <?=$comment->text?>
    <br>
    <?=$comment->date?>
    <br>
    автор поста:  <?=$comment->user->login?>
    <br>
    <br>
    <?php
    }

    if (!Yii::$app->user->isGuest) {

    $form = ActiveForm::begin([
            'action' => ['comment/create','id' => $post->id],
    ]);

    echo $form->field($model, 'text');
    ?>

    <div class="form-group">
    <?= Html::submitButton('Добавить', ['class' => 'btn btn-primary', 'name' => 'create-button']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

<?php
    }
    ?>
</div>